#!/bin/bash

# This is a sample build script for Java/maven projects. It runs unit tests, integration tests 
# and when they succeed, it packages the build and copies the artifact to where it runs in production. 
# When any of the steps fails, it stops immediately. 
#
# You should adapt it to your setup. That means directories, types of tests and the name of the user
# that does the automated building, but at the very minimum, adjust _projectname_ to the name of your project.

cd /var/home/builduser/_projectname_/work/

echo 'Running unit tests'
mvn clean install
rc=$?
if [[ $rc -ne 0 ]] ; then
  exit $rc
fi

echo 'Running integration tests'
mkdir config
cp ../resources/test/*properties ./config/
mvn clean test -Dtest=*IT -D_projectname_.config="./config/"
rc=$?
if [[ $rc -ne 0 ]] ; then
  exit $rc
fi

echo 'Packaging target'
mvn clean package
cp target/_projectname_*jar /opt/_projectname_/_projectname_.jar

echo 'Cleaning workspace'
rm -rf *

echo 'Finished deployment succesfully'
 
